export const INSERT_LOGIN = "INSERT_LOGIN"; 
export const INSERT_LOGIN_SUCCESS = "INSERT_LOGIN_SUCCESS"; 
export const INSERT_LOGIN_ERROR = "INSERT_LOGIN_ERROR"; 

export const RESET_INSERT_LOGIN = "RESET_INSERT_LOGIN"; 
export const RESET_INSERT_LOGIN_SUCCESS = "RESET_INSERT_LOGIN_SUCCESS"; 
export const RESET_INSERT_LOGIN_ERROR = "RESET_INSERT_LOGIN_ERROR"; 

export const LOGOUT = "LOGOUT"; 
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"; 
export const LOGOUT_ERROR = "LOGOUT_ERROR"; 

export const RESET_INSERT_LOGOUT = "RESET_INSERT_LOGOUT"; 
export const RESET_INSERT_LOGOUT_SUCCESS = "RESET_INSERT_LOGOUT_SUCCESS"; 
export const RESET_INSERT_LOGOUT_ERROR = "RESET_INSERT_LOGOUT_ERROR"; 