export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";
export const GET_USER_LIST_ERROR = "GET_USER_LIST_ERROR";

export const ADD_USER_LIST = "ADD_USER_LIST";
export const ADD_USER_LIST_SUCCESS = "ADD_USER_LIST_SUCCESS";
export const ADD_USER_LIST_ERROR = "ADD_USER_LIST_ERROR";

export const DELETE_USER_LIST = "DELETE_USER_LIST";
export const DELETE_USER_LIST_SUCCESS = "DELETE_USER_LIST_SUCCESS";
export const DELETE_USER_LIST_ERROR = "DELETE_USER_LIST_ERROR";